os: osx
env:
  global:
    - DEPLOYMENT_NAME=spacegame
    - DEPLOYMENT_TTL=ttl_1_hours
    - ASSEMBLY_NAME=spacegame_$TRAVIS_JOB_NUMBER
cache:
  timeout: 3600
  directories:
    - $HOME/Library/Caches/Homebrew
notifications:
  email:
    - andrea@improbable.io
before_install:
  - chmod a+x ./ci/deploy_secret.sh
  - chmod a+x ./ci/install.sh
  - chmod a+x ./ci/tear_down.sh
  - chmod a+x ./ci/build.sh
  - chmod a+x ./ci/test_local.sh
  - chmod a+x ./ci/test_cloud.sh
install:
  - "./ci/install.sh"
before_script:
  - "./ci/deploy_secret.sh"
  - "./ci/tear_down.sh"
script:
  - "./ci/build.sh"
  - if [ $TRAVIS_TEST_RESULT -eq 0 ]; then ./ci/test_local.sh; fi
  - if [ $TRAVIS_TEST_RESULT -eq 0 ]; then ./ci/test_cloud.sh; fi
before_cache:
  - brew cleanup