os: osx
rvm:
  - 2.3.7
env:
  global:
    - HOMEBREW_FOLDER=$HOME/Library/Caches/Homebrew
    - DEPLOYMENT_NAME=spacegame
    - DEPLOYMENT_TTL=ttl_1_hours
    - ASSEMBLY_NAME=spacegame_$TRAVIS_JOB_NUMBER
cache:
  timeout: 3600
  directories:
    - "$HOMEBREW_FOLDER"
notifications:
  email:
    - andrea@improbable.io
before_install:
  - chmod a+x ./ci/secret.sh
  - chmod a+x ./ci/install.sh
  - chmod a+x ./ci/tear_down.sh
  - chmod a+x ./ci/build.sh
  - chmod a+x ./ci/test_local.sh
  - chmod a+x ./ci/deploy.sh
  - rvm --default use 2.3.7
install:
  - "./ci/install.sh"
before_script:
  - "./ci/secret.sh"
  - "./ci/tear_down.sh"
script:
  - "./ci/build.sh"
  - if [ $TRAVIS_TEST_RESULT -eq 0 ]; then ./ci/test_local.sh; fi
  - if [ $TRAVIS_TEST_RESULT -eq 0 ]; then ./ci/deploy.sh; fi
after_script:
  - curl --upload-file $(ls -t $TRAVIS_BUILD_DIR/SpatialOS/logs/spatial_* | head -n 1) "https://transfer.sh/spatial_$TRAVIS_BUILD_NUMBER.log"
